
services:
  cpanel_update:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpanel_update
    restart: unless-stopped
    environment:
      CPANEL_ADDRESS: ${CPANEL_ADDRESS}
      CPANEL_USERNAME: ${CPANEL_USERNAME}
      CPANEL_PASSWORD: ${CPANEL_PASSWORD}
      DOMAIN: ${DOMAIN}
      RECORD: ${RECORD}
      TTL: ${TTL}
      EVERY: ${EVERY}